=== shlomif/Fiction-XML/perl/modules/XML-Grammar-Fiction/extradata/screenplay-xml.dtd
<!ELEMENT document (head,body)>
<!ELEMENT head EMPTY>
<!ELEMENT body (scene+)>
<!ELEMENT scene ((description|saying)*,scene*)>
<!ELEMENT description (para+)>
<!ELEMENT saying (para+)>
<!ELEMENT para (#PCDATA|inlinedesc|ulink|bold|br)*>
<!ELEMENT inlinedesc (#PCDATA|ulink|bold)*>
<!ELEMENT ulink (#PCDATA|bold)*>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT br EMPTY>
<!ATTLIST scene id ID #REQUIRED title CDATA #IMPLIED>
<!ATTLIST body id ID #REQUIRED>
<!ATTLIST saying character CDATA #REQUIRED>
<!ATTLIST ulink url CDATA #REQUIRED>

=== shlomif/Fiction-XML/perl/modules/XML-Grammar-Fiction/t/screenplay/data/xml/dialogue-with-several-paragraphs.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE document SYSTEM "screenplay-xml.dtd">
<document xmlns="http://web-cpan.berlios.de/modules/XML-Grammar-Screenplay/screenplay-xml-0.2/">
    <head>
    </head>
    <body id="index">
<scene id="top">
    <scene id="david_and_goliath">
        <saying character="David">
            <para>
                I will kill you.
            </para>
        </saying>
        <saying character="Goliath">
            <para>
                no way, you little idiot!
            </para>
        </saying>
        <saying character="David">
            <para>
                yes way!
            </para>
            <para>
                In the name of Allah, the merciful, I will show you the power 
                of my sling.
            </para>
            <para>
                I shall sling you and bing you till infinity.
            </para>
        </saying>
        <saying character="Goliath">
            <para>
                I'm still waiting.
            </para>
        </saying>
        <saying character="David">
            <para>
                so you are.
            </para>
        </saying>
    </scene>
</scene>
</body>
</document>

=== shlomif/Fiction-XML/perl/modules/XML-Grammar-Fiction/t/screenplay/data/xml/scenes-with-titles.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE document SYSTEM "screenplay-xml.dtd">
<document xmlns="http://web-cpan.berlios.de/modules/XML-Grammar-Screenplay/screenplay-xml-0.2/">
    <head>
    </head>
    <body id="index">
        <scene id="top">
            <scene id="a-better-scene" title="A Better Scene">
            </scene>
            <scene id="another-scene">
            </scene>
            <scene id="exodus" title="The Exodus">
                <saying character="Moses">
                    <para>
                        let us get out of here!
                    </para>
                </saying>
                <saying character="Joshua">
                    <para>
                        amen!
                    </para>
                </saying>
            </scene>
        </scene>
    </body>
</document>

=== shlomif/Fiction-XML/perl/modules/XML-Grammar-Screenplay/t/data/xml/with-internal-description.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE document SYSTEM "screenplay-xml.dtd">
<document xmlns="http://web-cpan.berlios.de/modules/XML-Grammar-Screenplay/screenplay-xml-0.2/">
    <head>
    </head>
    <body id="index">
<scene id="top">
    <scene id="david_and_goliath">
        <description>
            <para>
                David and 
                <ulink url="http://en.wikipedia.org/wiki/Goliath">Goliath</ulink> 
                are standing by each other.
            </para>
        </description>
        <saying character="David">
            <para>
                I will kill you.
            </para>
        </saying>
        <saying character="Goliath">
            <para>
                no way, you little idiot!
            </para>
        </saying>
        <saying character="David">
            <para>
                yes way!
            </para>
            <para>
                In the name of <ulink url="http://real-allah.tld/">Allah, the <bold>merciful</bold>, real merciful</ulink>, I will show you the 
                <inlinedesc>sarcastically</inlinedesc> power 
                of my sling.
            </para>
            <para>
                I shall sling you and bing you till infinity.
            </para>
        </saying>
        <description>
            <para>
                David takes his sling.
            </para>
        </description>
    <saying character="Goliath">
        <para>
            I'm still <ulink url="http://wait.tld/">waiting</ulink>.
        </para>
    </saying>
    <saying character="David">
        <para>
            so you are.
        </para>
    </saying>
    <description>
        <para>
            David puts a stone in his sling and shoots Goliath. He hits.
        </para>
    </description>
    <saying character="David">
        <para>
            as is written in the wikipedia <inlinedesc>See <ulink url="http://wiki.tld/">the Wiki site</ulink>
                for more information</inlinedesc>, you are now dead,
            having been shot with my sling.
        </para>
    </saying>
</scene>
</scene>
</body>
</document>

=== shlomif/Fiction-XML/perl/modules/XML-Grammar-Fiction/t/fiction/data/xml/with-brs.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE document SYSTEM "screenplay-xml.dtd">
<document xmlns="http://web-cpan.berlios.de/modules/XML-Grammar-Screenplay/screenplay-xml-0.2/">
    <head>
    </head>
    <body id="index">
<scene id="top">
    <scene id="david_and_goliath">
        <description>
            <para>
                David and 
                <ulink url="http://en.wikipedia.org/wiki/Goliath">Goliath</ulink> 
                are standing by each other.
            </para>
        </description>
        <saying character="David">
            <para>
                I will kill you.<br />
                I will kill you.<br />
                You will not survive.<br />
                I will kill you.<br />
                I will kill you.<br />
                Ask Jive.
            </para>
        </saying>
        <saying character="Goliath">
            <para>
                no way, you little idiot!
            </para>
        </saying>
        <saying character="David">
            <para>
                yes way!
            </para>
        </saying>
</scene>
</scene>
</body>
</document>
